### ISSUE TITLE
Resetting dynamically rendered loadingButton fails

### ISSUE THREAD

**Issue by matthijsvanderloos** [merlinoa/shinyFeedback#50] opened 2020-10-21 12:38 UTC
I have a Shiny app that uses `shiny::renderUI()` to dynamically render a `shinyFeedback::loadingButton()`. Despite the button being rendered correctly, calling `shinyFeedback::resetLoadingButton()` later on fails to actually reset the button.

From my analysis it seems the message handler for `resetLoadingButton` is attached in `loadingButton.js` (https://github.com/merlinoa/shinyFeedback/blob/master/inst/assets/js/loadingbutton.js#L77-L82) on the `shiny:sessioninitialized` event. I guess this event has already been triggered before the button is rendered (and `loadingButton.js` is loaded).

Reprex:

``` r
library(shiny)
library(shinyFeedback)


ui <- fluidPage(
  title = "Shinyfeedback loading button",
  fluidRow(
    column(width = 4,
      uiOutput("lb"),
      actionButton("stop_btn", "Stop searching")
    )
  )
)

server <- function(input, output, session) {
  output$lb <- renderUI({
      loadingButton("loadingbutton", label = "Search", loadingLabel = "Searching...")
      
  })
  
  observeEvent(input$stop_btn, {
    # The following does not reset the loading button
    resetLoadingButton("loadingbutton")    
  })
  
}

shinyApp(ui = ui, server = server)
```

**Comment by phoward38** [comment] 2020-10-21 14:40
Hey @matthijsvanderloos,

Thanks for the informative issue & reprex! You're correct about the cause of the issue. We plan to have this fixed in the next minor CRAN release of `shinyFeedback`.

Feel free to make a PR if you need this addition ASAP. Otherwise, I'll update you on the fix as soon as it's added to the development version.

**Closed as completed** 2020-10-21 19:55 UTC

**Comment by merlinoa** [comment] 2020-10-21 19:57
Yes thanks very much @matthijsvanderloos.  Excellent reprex and issue!  I just pushed a fix to master.  Please reopen if that did not resolve the issue.

**Comment by matthijsvanderloos** [comment] 2020-10-22 07:41
Hi @phoward38, @merlinoa,

Thanks for the quick response! I have tested the fix and it indeeds resolves the issue.
