### ISSUE TITLE
feedbackWarning, feedbackDanger, feedbackSuccess do not dynamically remove text when passed a variable containing a character object and number is changed quickly

### ISSUE THREAD

**Issue by samhiggs** [merlinoa/shinyFeedback#47] opened 2020-08-20 23:06 UTC
Using the below hopefully reproducible example...
If you go from a negative to a positive number reasonably quickly the warning/error/success text will hang
If you double click on the number then type a positive number the warning/error/success  text will hang
If you slowly backspace twice then select a positive number the warning/error/success text will hang

Using R3.5.1

```
library(shiny)
library(shinyFeedback)

ui <- fluidPage(
        useShinyFeedback(),

        numericInput(
          "exampleInput",
          "Show Feedback When < 0",
          value = -5
        ))

server <- function(input, output) {

    v <- function(n) {
        if (is.na(n)) {return("I am NA")}
        if (n < 0) {return("I am negative")}
        return("")
    }
    
    observeEvent(input$exampleInput, {
        text <- v(input$exampleInput)
        feedbackWarning(
          "exampleInput",
          text != "",
          text = text,
          color = "#d9534f",
          icon = shiny::icon("exclamation-sign", lib="glyphicon")
        )
    })
}

shinyApp(ui, server)
```

Here are the images that demonstrate the issue
![feedback1](https://user-images.githubusercontent.com/18094032/90834164-f2673c80-e38c-11ea-8400-d7891778a32c.PNG)
![feedback2](https://user-images.githubusercontent.com/18094032/90834159-f004e280-e38c-11ea-9a17-8334b5ccc336.PNG)
![feedback3](https://user-images.githubusercontent.com/18094032/90834162-f1360f80-e38c-11ea-847a-cf271a0ba15e.PNG)
![feedback4](https://user-images.githubusercontent.com/18094032/90834400-8f29da00-e38d-11ea-8c01-f4b22656584e.PNG)

**Comment by phoward38** [comment] 2020-09-03 19:57
Hi @samhiggs,

Thanks for using `shinyFeedback`. Hope you've enjoyed it so far!

I ran your reprex but was unable to reproduce the hanging text. Here is my relative session info:
- `R` v3.6.3
- `Shiny` v1.5.0
- `shinyFeedback` v0.2.0
- Also, I'm running my app in the browser, not the RStudio window.

Let me know if the issue is still occurring on your end using the R/package versions above & opening the app in a web browser

**Comment by merlinoa** [comment] 2020-09-23 10:28
I am going to close this issue out since we have not gotten a response.  Please reopen if you feel this is still an issue.

**Closed as completed by merlinoa** 2020-09-23 10:28 UTC
